### ISSUE TITLE
id column length limitation

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcbasins#4]
Because we are writing to temp shapefiles, we have to live by shapefile rules. 
Either force use of shorter id with script validation, handle this internally, or use some other format. 

```
0...10...20...30...40...50...60...70...80...90...100 - done.
Warning 6: Normalized/laundered field name: 'station_number' to 'station_nu'
Warning 6: Normalized/laundered field name: 'linear_feature_id' to 'linear_fea'
Warning 6: Normalized/laundered field name: 'wscode_ltree' to 'wscode_ltr'
Warning 6: Normalized/laundered field name: 'localcode_ltree' to 'localcode_'
Warning 6: Normalized/laundered field name: 'fwa_watershed_code' to 'fwa_waters'
Warning 6: Normalized/laundered field name: 'local_watershed_code' to 'local_wate'
Warning 6: Normalized/laundered field name: 'blue_line_key' to 'blue_line_'
Warning 6: Normalized/laundered field name: 'downstream_route_measure' to 'downstream'
Warning 6: Normalized/laundered field name: 'distance_to_stream' to 'distance_t'
Warning 6: Normalized/laundered field name: 'watershed_group_code' to 'watershed_'
0...10...20...30...40...50...60...70...80...90...100 - done.
Traceback (most recent call last):
  File "create_watersheds.py", line 175, in <module>
    create_watersheds()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "create_watersheds.py", line 120, in create_watersheds
    station_id,
  File "/Users/snorris/Projects/env/fish_passage/model/fwakit/fwakit/watersheds.py", line 418, in wsdrefine_dem
    id_type = src.schema["properties"][ref_id]
KeyError: 'station_number'
```

**Comment by smnorris** [comment]
closing - no more shapes
